name: hybrid-llm-classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - faiss-cpu=1.7.4
  - numpy=1.24.3
  # Development tools
  - black
  - isort
  - mypy
  - flake8
  - pytest
  - pytest-asyncio
  - pytest-cov
  - pip:
      - fastapi>=0.104.1
      - uvicorn>=0.24.0
      - python-jose[cryptography]>=3.3.0
      - python-multipart>=0.0.6
      - pydantic>=2.5.2
      - httpx>=0.25.2
      - python-dotenv>=1.0.0
      - prometheus-client>=0.19.0
      - pydantic-settings>=2.1.0
